### ISSUE TITLE
Bug needs to be fixed due to an upgrade to weblogic 12 1.3

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#35]
We need to upgrade our weblogic serivce and it caused a problem that we are currently fixing.

**Comment by dg-grow-virgiliu-ratoi** [comment]
Uploading file doesn't work on Weblogic 12.1.3 and spring boot 1.2.3.RELEASE.

The root of the problem is that OrderedCharacterEncodingFilter is running after HiddenHttpMethodFilter. HiddenHttpMethodFilter triggers processing of the request body as it calls getParameter on the request. OrderedCharacterEncodingFilter then runs and sets the request's encoding. Setting the request's encoding after its body has been processed is bad and, on WebLogic, causes the request to lose track of all its multipart data.

More details can be found at:
[https://github.com/spring-projects/spring-boot/issues/2862](url)
[https://github.com/spring-projects/spring-boot/issues/2148](url)

**Comment by tsirafa** [comment]
Envoyé via Email+, sécurisé et géré par MobileIron

________________________________

De : "Virgiliu Ratoi" <notifications@github.com<mailto:notifications@github.com>>
Date : mardi 9 août 2016 16:21:19
À : "ESPD/ESPD-Service" <ESPD-Service@noreply.github.com<mailto:ESPD-Service@noreply.github.com>>
Objet : Re: [ESPD/ESPD-Service] Bug needs to be fixed due to an upgrade to weblogic 12 1.3 (#35)


Uploading file doesn't work on Weblogic 12.1.3 and spring boot 1.2.3.RELEASE.

The root of the problem is that OrderedCharacterEncodingFilter is running after HiddenHttpMethodFilter. HiddenHttpMethodFilter triggers processing of the request body as it calls getParameter on the request. OrderedCharacterEncodingFilter then runs and sets the request's encoding. Setting the request's encoding after its body has been processed is bad and, on WebLogic, causes the request to lose track of all its multipart data.

More details can be found at:
https://github.com/spring-projects/spring-boot/issues/2862<url>
https://github.com/spring-projects/spring-boot/issues/2148<url>

**Comment by davideas** [comment]
Thank you to have investigated in this issue and found a solution before us, we saved lot of time.
We got same issue with Spring Boot 1.4.1 and Weblogic 12.1.3.

Davide
DG DIGIT B2
