### ISSUE TITLE
Part III: Section B: "Payment of taxes" and “Payment of social security”

### ISSUE THREAD

**Issue by ec-mcs** [ESPD/ESPD-Service#51]
In the exclusions tab, section B.

There is a serious translation error in the texts in Swedish regarding “Payment of taxes” as well as “Payment of social security”.

The error is omission of negation, making the question completely opposite to the original text.
It is the word “breached” that is omitted in the Swedish translation.

The result is that the English text asks you to answer “Yes” if you have breached your obligations.
The Swedish text asks you to answer “Yes” if you have fulfilled your obligations.

Goggle translates the Swedish text as follows:
“Has the economic operator met all its obligations regarding the payment of taxes, both in the country in which he is established and in the contracting authority or entity Member State if it is a country other than the country of establishment?”

Which is quite opposite to the original:
“Has the economic operator breached its obligations relating to the payment of taxes, both in the country in which it is established and in Member State of the contracting authority or contracting entity if other than the country of establishment?”

**Comment by ec-mcs** [comment]
![capture](https://cloud.githubusercontent.com/assets/20335285/17771805/760a9ff2-6545-11e6-9847-8df452a75658.PNG)

**Comment by ec-mcs** [comment]
The corrected SV messages file
[messages_sv.zip](https://github.com/ESPD/ESPD-Service/files/713207/messages_sv.zip)

**Comment by dg-grow-alexey-lukashov** [comment]
fixed on DEV

**Comment by dg-grow-alexey-lukashov** [comment]
fixed additional SV labels:

for payment of taxes, in Swedish : “Har den ekonomiske aktören åsidosatt sina skyldigheter i fråga om betalning av skatter, i det land där denne är etablerad eller i den upphandlande myndighetens eller enhetens medlemsstat om det är ett annat land än etableringslandet?”

for payment of social  security, in Swedish:
“Har den ekonomiske aktören åsidosatt  sina skyldigheter  i fråga om betalning av sociala avgifter, i det land där denne är etablerad eller i den upphandlande myndighetens eller enhetens medlemsstat om det är ett annat land än etableringslandet?” 

We have deleted alla , since there is no text saying “all” in the ESPD service(the English version), only in the Regulation. And then deleted “bade” and said “I  eller”  which is more correct Swedish when we change “uppfyllt” to” åsidosatt”.

**Comment by dg-grow-alexey-lukashov** [comment]
hotfixed
