### ISSUE TITLE
Temporary TED ID to be deleted if CA reuses request from .XML

### ISSUE THREAD

**Issue by ojlaranjo** [ESPD/ESPD-Service#82]
We had an authority who approached us with an issue: the problem was that if they reused it as a CA the info about the procurement procedure was different then when they imported it as a EO.
[espd-request_112_16.zip](https://github.com/ESPD/ESPD-Service/files/461518/espd-request_112_16.zip)

Solution: if an authority reuses an XML the temporary ID should be deleted.

**Comment by dg-grow-virgiliu-ratoi** [comment]
We will not override the identity of the procurer and the information about the procurement procedure any more in case at least one of the containing fields is filled in.

**Comment by dg-grow-virgiliu-ratoi** [comment]
In case we are an EO and we import an ESPD Request with a temporary id we agreed that we should not override the procurer and procurement procedure information if at least one field is filled in. However, it makes sense in this scenario to still update the notice number and OJS URL with information coming from TED.

**Comment by dg-grow-virgiliu-ratoi** [comment]
In case you are a CA and you reuse the same ESPD Request we will make the Temporary ID visible in the Part I 'Information about publication' section. So if it is available, the OJS number and URL would be visible. If the user then deletes the Temporary ID because it is not the correct one we would delete the content of the OJS number and URL.

**Comment by ec-mcs** [comment]
Ok for me!
