### ISSUE TITLE
Export an ESPD as PDF

### ISSUE THREAD

**Issue by dg-grow-virgiliu-ratoi** [ESPD/ESPD-Service#97]
Using the code coming from Tenderned at https://github.com/Robert-Smit/espd/tree/TenderNed

**Comment by hofdesir** [comment]
I don't have much time to debug this issue, but it has to do with the encoding in the html. 
Best way to debug this issue is to add this method in the TenderNedUtils class:

```
    public void saveHtml(String html) throws IOException {
        FileUtils.writeStringToFile(new File("D:/html.html"), html, "UTF-8");
    }
```
although I'm not sure if "UTF-8"is the right Charset for Greek characters. You should check that on the internet.

You can add the method in
`public String addHtmlHeader(String html) throws IOException { 
`
which is on line 79.


The html comes from the print.jsp page and is passed on with a hidden input:

```
  <input type="hidden"
           name="html"
           value="${fn:escapeXml(applicationScope.cachedFragment)}" />
```

The html is passed on with the greek characters from the print.jsp, but when it's being saved as a String in EspdDocument, all the extended characters become '?'.

**Comment by dg-grow-virgiliu-ratoi** [comment]
It's not related to the encoding, that is fine. There is a warning in the logs that says: Glyph "ț" (0x21b) not available in font "Times-Bold". This applies to the standard font families like: Arial, Times, Helvetica for all non-ASCII characters.

**Comment by dg-grow-virgiliu-ratoi** [comment]
Every font contains a particular set of glyphs. If no glyph can be found for a given character, FOP will issue a warning and use the glyph for "#" (if available) instead. We need to use a font that contains all the glyphs for the European languages. DejaVu is such a font.

**Comment by dg-grow-virgiliu-ratoi** [comment]
In order to use a custom font like DejaVu, we need to run the _org.apache.fop.fonts.apps.TTFReader_ main method with parameters like _DejaVuSans.ttf dejavusans.xml_. This will generate the xml file containing the configuration of the font.

The font can then be added in the FOP config xml file inside the 'application/pdf' renderer:
`<font metrics-url="fonts/dejavusans.xml" embed-url="fonts/DejaVuSans.ttf">
   <font-triplet name="DejaVuSans" style="normal" weight="normal"/>
  </font>`

**Comment by tsirafa** [comment]
The issue should be re-opened as in ACC and PROD , PRINTING does not work properly. The Weblogic servers should be configured in the same way with the DEV one.

**Comment by dg-grow-virgiliu-ratoi** [comment]
We had to copy the fonts on our ACC and PROD machines and load them via absolute paths.

**Comment by ec-mcs** [comment]
Its fixed so let's close it...
